# Создание нового пользователя.
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "faya_sobaka1@dog.rus",
  "name": "Faya",
  "isPro": true,
  "password": "super!"
}
###

## Вход в закрытую часть приложения.
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "faya_sobaka1@dog.rus",
  "password": "super!"
}
###

## Проверка состояния пользователя.
GET http://localhost:3000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3MmE3ODdiOWJmZDIyY2U5MGU5MjRlOSIsImVtYWlsIjoibmV3X3VzZXIxMjM0NUB0ZXN0LmNvbSIsIm5hbWUiOiJBZG1pbiIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MzA4MzY2MTcsImV4cCI6MTczMTAwOTQxN30.yPXUcmXt8GsIasBoZ7mWDSfU6HHDNRtEUL4kAnaT08g
###

## Выход из закрытой части приложения.

DELETE http://localhost:3000/users/logout HTTP/1.1
