#
##

POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Beautiful & luxurious studio at great location",
  "postDate": "2019-05-08T14:13:56.569Z",
  "previewImage": "https://url-to-image/image.png",
  "type": "apartment",
  "price": "120",
  "city": "Amsterdam",
  "isFavorite": "false",
  "isPremium": "false",
  "rating": "4",
  "description": "A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.",
  "bedrooms": "3",
  "goods": [{"Heating"}],
  "host": {
    "name": "Oliver Conner",
    "avatarUrl": "https://url-to-image/image.png",
    "email": "123_dd@im.com",
    "password": "string",
    "typeUser": "Pro",
    },
  "images": [{"https://url-to-image/image.png"}],
  "maxAdults": "4"
}
