# Добавление комментария для предложения.
POST http://localhost:3000/comments/ HTTP/1.1
Content-Type: application/json

{
  "offerId": "6720b0971e31660a634b0b59",
  "comment": "A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam.",
  "rating": 2,
  "userId": "6724fbf1d5ea880524230291"
}

###
